server:
  port: 8087
  
spring:
  application:
    name: API-GATEWAY
  
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
      routes:
        - id: ADMIN-SERVICE
          uri: http://localhost:8081
          predicates:
            - Path=/flights/**
            
        - id: SEARCH-SERVICE
          uri: http://localhost:8082
          predicates:
            - Path=/flightDetails/search/**
            
        - id: BOOK-SERVICE
          uri: http://localhost:8083
          predicates:
            - Path=/BookFlights/book/**
            
      
